In [ ]:
_<font color='blue'>Actividad de Aprendizaje</font>_

In [ ]:
_<font color='blue'>Nombre: Maricela Maldonado</font>_

_<font color='blue'>1. Utilizando los metodos Newton, Bisección y Secante encuentre la raíz de la siguiente función: $f(x) = x + cos (x) $ en el intervalo $[−2, 0]$, con cuatro cifras decimales.</font>_


<img src="EJE1.png">

**_<font color='blue'>Metodo Bisección</font>_**

In [1]:
#### Importamos librerias ###
import numpy as np
def biseccion2(f,a,b,tol):
    if np.sign(f(a)) == np.sign(f(b)):
        print("La raiz no esta en el intervalo que esta especificado")
        return
    m = (a + b)/2
    if np.abs(f(m)) < tol:
        return m
    elif np.sign(f(a)) == np.sign(f(m)):
        return biseccion2(f, m, b, tol)
    elif np.sign(f(b)) == np.sign(f(m)):
        return biseccion2(f, a, m, tol)
    
#f = lambda x: x*np.cos(x)-3
f= lambda x: x+np.cos(x)

#r1 = biseccion(f, 1, 2, 0.0001,100)
biseccion2(f, -2, 0, 0.0001)
#print("error =", np.sqrt(2)-r1)
#print("error =", (5.312469-r2))


-0.7391357421875

**_<font color='blue'> Metodo Newton </font>_**

In [2]:
import numpy as np
def biseccion2(f,a,b,tol):
    if np.sign(f(a)) == np.sign(f(b)):
        print("La raiz no esta en el intervalo que esta especificado")
        return
    m = (a + b)/2
    if np.abs(f(m)) < tol:
        return m
    elif np.sign(f(a)) == np.sign(f(m)):
        return biseccion2(f, m, b, tol)
    elif np.sign(f(b)) == np.sign(f(m)):
        return biseccion2(f, a, m, tol)
    
#f = lambda x: x*np.cos(x)-3
f= lambda x: x+np.cos(x)

#r1 = biseccion(f, 1, 2, 0.0001,100)
biseccion2(f, -2, 0, 0.0001)
#("error =", np.sqrt(2)-r1)
#print("error=", (5.312469-r2))


-0.7391357421875

**_<font color='blue'>Metodo Secante</font>_**

In [3]:
import numpy as np
def secante(f,x0,x1,nmax,tol):
    for i in range(0,nmax):
        x2=(x0*f(x1)-x1*f(x0))/(f(x1)-f(x0));
        if abs(x2-x1) < tol:
            print(x2,' localizado con ',i,' interacciones')
            break
        else:
            x0=x1
            x1=x2
    return None

#f = lambda x: x*np.cos(x)-3
f=lambda x: x+np.cos(x)
secante(f,-2,0,20,1e-10)

-0.7390851332151606  localizado con  6  interacciones


_<font color='blue'>2. Encontrar la interseccion de las siguientes funciones: $f(x) = 3 − x$ y $g(x) = ln (x)$, con tres cifras decimales.</font>_

In [ ]:
_<font color='red'> Primero igualamos las funciones</font>_

##### $f\left(x\right)\:=\:g\left(x\right)\:\rightarrow \:3-x\:=\:ln\left(x\right)$

#####  Desarrollando
#####  $ln\left(x\right)\:+x-3=0$
#####  $i\left(x\right)=ln\left(x\right)+x-3\:$
#####  $i'\left(x\right)=\frac{1}{x}+1$

#####  Definir raíces de $i$
#####  $x_0=2\:;\:i=0$
#####  $i\left(2\right)=ln\left(2\right)+2-3\:\rightarrow \:-0,307$
#####  $i'\left(2\right)=\frac{1}{2}+1\:=\frac{3}{2}\:\rightarrow \:1,5$

#####  Evaluamos en Newton
#####  $x_1=2-\left(\frac{-\:0,307}{1,5}\right)\:$
##### $x_1=2,20466\:\rightarrow \:2,205$

#####  Evaluamos $i=1 ; x_1=2,205$
#####  $i\left(2,205\right)\:=\:ln\left(2,205\right)+2,205\:-\:3\:\rightarrow \:-0,004$
#####  $i'\left(2,205\right)\:=\frac{1}{2,205}\:+\:1\:=\:1,4535\:\rightarrow \:1,454$
#####  $x_2\:=\:2,205\:-\left(\frac{-\:0,004}{1,454}\right)\:\rightarrow \:x_2=2,208$

#####  Evaluamos $i =2 ; x_3 = 2,208$
##### $i\left(2,208\right)\:=ln\left(2,208\right)\:+2,208\:-\:3\:=0,00008\:\rightarrow \:0,000$
##### $i'\left(2,208\right)\:=\frac{1}{2,208}\:+\:1\:=1,453$

##### Evaluamos en $x_3$
##### $x_3\:=\:x_2\:-\frac{i\left(x_2\right)}{i'\left(x_2\right)}$
##### $x_3=2,208\:-0\:\rightarrow \:2,208$

#####  Se reemplaza la raíz 
#####  Si $f(x) = 3 - (x)$
##### $f(2,208) = 3 - 2,208 \rightarrow \:0,792$ 
#####  $Respuesta./ \:La\:interseccion\:de\:las\:funciones\:es:\:\left(2,208\:;\:0,792\right)$

_<font color='blue'> 3. Programar el metodo de sustitucion regresiva. Analice el numero de operaciones del algoritmo para matrices de tamaño 3 × 3.</font>_

In [3]:
import numpy as np
# ingreso la matriz
A = np.array([[1,1,-3],[0,1,1],[0,0,3]])
# terminos independientes
b=np.array([0,1,3])
#el numero de ecuaciones 3 filas
n=np.size(b)
#Se define el vector para colocar la solucion
x=np.zeros(n)
#realizamos el ciclo que va desde la ultima ecuacion hasta la primera
for i in range(n-1,-1,-1):
    sumj=0
    for j in range (i+1,n):
        sumj +=A[i,j]*x[j]
    x[i]=(b[i]-sumj)*1/A[i,i]
print(x)

[3. 0. 1.]


_<font color='blue'> 4.Una importante parte de la física es la termodinámica que es el estudio de la transferencia de calor.En este ejercicio vamos a determinar la distribución de temperatura de estado estable de una placa delgada cuando se conoce la temperatura en los bordes.Suponga que la placa que se ilustra en la figura representa una sección transversal de una viga de metal, con flujo de calor despreciable en la dirección perpendicular a la placa. Sean T1, T2, T3 yT4 las temperaturas en los cuatro nodos interiores de la malla en la figura. La temperatura en unnodo es aproximadamente igual al promedio de las temperaturas de los cuatro nodos más cercanos,esto es, a la izquierda, arriba, a la derecha y abajo.Escriba un sistema de ecuaciones cuya solución de estimaciones de las temperaturas T1, T2, T3 y T4.Programe el método de eliminación gaussiana. </font>_

<img src="EJE4.png">

In [1]:
import numpy as np
A = np.array([[4., -1., -1.,  0.],
              [-1., 4.,  0., -1.],
              [-1., 0.,  4., -1.],
              [0., -1., -1., 4.]])
B = np.array([30.,60.,40.,70.])
A1=np.copy(A)
B1=np.copy(B)
n=len(B)
print(A)
print(B)
for k in range(0,n-1):
    for i in range(k+1,n):
        mult= A[i,k]/A[k,k]
        for j in range(k,n):
            A[i,j]-=mult*A[k,j]
        B[i] -=mult*B[k]
x=np.zeros(n)
x[n-1]=B[n-1]/A[n-1,n-1]
for i in range(n-2,-1,-1):
    suma_j=0
    for j in range(i+1,n):
        suma_j += A[i,j]*x[j]
        x[i]=(B[i]-suma_j)/A[i,i]

print("\n Soluciones del sistema de  ecuaciones  es:")
print(np.linalg.solve(A,B))

[[ 4. -1. -1.  0.]
 [-1.  4.  0. -1.]
 [-1.  0.  4. -1.]
 [ 0. -1. -1.  4.]]
[30. 60. 40. 70.]

 Soluciones del sistema de  ecuaciones  es:
[20.  27.5 22.5 30. ]


_<font color='blue'> 5. Programe el pivoteo parcial en el algoritmo de eliminación gaussiana. Utilice este nuevo programa para resolver el ejercicio anterior. Compare los resultados.</font>_

In [6]:
import numpy as np
A = np.array([[0., -1., -1.,  0.],
              [-1., 4.,  0., -1.],
              [-1., 0.,  4., -1.],
              [0., -1., -1., 4.]])
B = np.array([30.,60.,40.,70.])
A1=np.copy(A)
B1=np.copy(B)
n=len(B)
print(A)
print(B)
for k in range(n-1):
        #Elija el elemento de pivote más grande a continuación (incluido) k
        maxindex = abs(A[k:,k]).argmax()+ k
        if A[maxindex, k] == 0:
            raise ValueError("Matrix is singular.")
        #Intercambiar filas
        if maxindex != k:
            A[[k,maxindex]] = A[[maxindex, k]]
            B[[k,maxindex]] = B[[maxindex, k]]
for k in range(0,n-1):

    for i in range(k+1,n):
        mult= A[i,k]/A[k,k]
        for j in range(k,n):
            A[i,j]-=mult*A[k,j]
        B[i] -=mult*B[k]
x=np.zeros(n)
x[n-1]=B[n-1]/A[n-1,n-1]
for i in range(n-2,-1,-1):
    suma_j=0
    for j in range(i+1,n):
        suma_j += A[i,j]*x[j]
        x[i]=(B[i]-suma_j)/A[i,i]

print("\n las soluciones del sistema de  ecuaciones  es:")
print(np.linalg.solve(A,B))

[[ 0. -1. -1.  0.]
 [-1.  4.  0. -1.]
 [-1.  0.  4. -1.]
 [ 0. -1. -1.  4.]]
[30. 60. 40. 70.]

 las soluciones del sistema de  ecuaciones  es:
[-120.   -12.5  -17.5   10. ]


_<font color='blue'> Bibliografia</font>_

_<font color='blue'> https://www.youtube.com/watch?v=QE0ZN4-MrKs</font>_

_<font color='blue'> https://yoursdata.net/jupyter-lab-shortcut-and-magic-functions-tips/?id_curso=18970</font>_

_<font color='blue'>http://esfm.egormaximenko.com/numlinalg/triangular_systems_of_linear_equations_es.pdf</font>_